gui:
  theme:
    selectedLineBgColor:
      - reverse
git:
  log:
    showGraph: 'always'
customCommands:
  - key: '<c-g>'
    command: "git push origin HEAD:refs/for/{{.CheckedOutBranch.Name}}"
    showOutput: true
    context: 'global'
    loadingText: 'pushing'
    prompts:
    - type: 'confirm'
      title: 'Push to origin/{{.CheckedOutBranch.Name}}'
      body: "Are you sure you want to push to origin/{{.CheckedOutBranch.Name}}?\n('enter' to push, else 'esc' to cancel)"
  - key: '<c-u>'
    command: "git submodule update --init --recursive"
    context: 'global'
    loadingText: 'updating'
